### PR TITLE
Added Nsis installer => now working without Nsis on Path

### PR DESCRIPTION
**Pull request by dobermai**
Hi!

I added the NSIS Installer to tomighty and configured the nsis plugin in the pom.xml, so we do not have to put makensis on path. 

The next step will be to get NSIS via Maven (tomighty repo??) or via the Wagon Plugin.

I hope this works, this is my first git commit :)

Greetings,

Dominik

### CODE REVIEW

**Comment by ccidral** [comment]
Hi Dominik,

That's great!  I think we should focus on making Maven download NSIS during the build, so we remove the burden of downloading NSIS when cloning the git repo.  Maybe we could make NSIS a dependency, as you have suggested, so that Maven knows when it is already present on the local repo, but I don't know whether that's possible or not.

I will be very busy for the next 2 weeks, but I will try my best to find some spare time to work on this issue.

Thanks for this amazing contribution!  :-)

Let's keep in touch.

Célio

**Comment by dobermai** [comment]
Ok, now it downloads nsis, packages tomighty and removes nsis again.

Sorry for my premature pull request. Now it should work really smooth :)

**Comment by ccidral** [comment]
No problem :)

Great job! I have one more suggestion: what do you think about leaving NSIS there instead of deleting it after the build?  So it would not be downloaded every time we need to generate the installer.

There's something else I would like to suggest but I think it's not important now.  It's about executing NSIS under a different profile.  I think that generating the installer is something we normally do only when making a public release of Tomighty, so by putting the NSIS plugin under a different profile people would not have to download NSIS in order to make a regular build.  But that's something we could do another day.

**Comment by dobermai** [comment]
Ok, added your feature wishes :)

**Comment by ccidral** [comment]
Thanks Dominik!  I will pull your changes into Tomighty's master.  But first I need to learn how to do that  :)

**Comment by ccidral** [comment]
I was wondering if by pulling all those changes into Tomighty's master would add NSIS to the repository history. Just in case, you could clone Tomighty's repo, make the necessary changes to the pom.xml file and commit it directly, what do you think? I guess it's just a matter of adding you as a collaborator. I could make the changes and commit, but I think it's fair that you keep the credits on the changes you made by having your name in the repo's history.

**Comment by ccidral** [comment]
Your changes were merged into Tomighty's master. Thanks!

**Pull request closed without merging**
